### ISSUE TITLE
bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3363 vrong name

### ISSUE THREAD

**Issue by robertwol** [cloudfoundry/bosh-linux-stemcell-builder#1]
latest stemcell 3363 http://bosh.cloudfoundry.org/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent

has wrong name when uploaded

**Comment by cppforlife** [comment]
@robertwol we are about to promote 3363.1 that will fix this problem.

**Comment by cppforlife** [comment]
Fixed in later 3363.x stemcells.
