### ISSUE TITLE
Base os image file name mismatches in ubuntu-xenial.meta4 and Rakefile

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-linux-stemcell-builder#106]
I'm building ubuntu xenial stemcell `456.40` for SoftLayer and found the following issue.

The file name of base os image specified in https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-xenial/v456.40/bosh-stemcell/image-metalinks/ubuntu-xenial.meta4#L2 has been changed to `ubuntu-xenial.tgz` from previous `bosh-ubuntu-xenial-os-image.tgz`. But in the Rakefile https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-xenial/v456.40/Rakefile#L61, the resolved meta4 download filename specified after `--file` is still `bosh-ubuntu-xenial-os-image.tgz` which makes the download failed due to error `File does not exist`.

Would you please fix the issue? Thanks.

**Comment by gu-bin** [comment]
Any update?

**Comment by jaresty** [comment]
I pushed a fix for this today.  Let us know if you still have issues.
