### ISSUE TITLE
/etc/machine-id is not unique

### ISSUE THREAD

**Issue by felixhuettner** [cloudfoundry/bosh-linux-stemcell-builder#122]
Hi everyone,

currently all instances of a stemcell have the exactly identical /etc/machine-id file. As per the [systemd documentation](https://www.freedesktop.org/software/systemd/man/machine-id.html) the /etc/machine-id is expected to be unique.

The duplication of the machine-id causes instances to use the same dhcp client identifier when running a dhcp client (e.g. systemd-networkd). This in turn causes dhcp-servers get dhcp-discovers from multiple different VMs with the same client-identifer. Because of that the system can shortly loose it's ip-address which can cause various issues (similar to [this](https://github.com/systemd/systemd/issues/9609#issuecomment-501139399)).

It seems to be that debootstrap is copying the machine-id to the target system in /etc/machine-id (see [systemd.postinst](https://bazaar.launchpad.net/~ubuntu-branches/debian/sid/systemd/sid/view/head:/debian/systemd.postinst#L102))

The solution would be to delete the /etc/machine-id file after debootstrap; systemd will recreate them at the first boot.
I would guess that [base_deboostrap/apply.sh](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/stemcell_builder/stages/base_debootstrap/apply.sh#L23) is the proper location for such a fix?

Best Regards

Felix

**Comment by felixhuettner** [comment]
FYI: link to the ubuntu manpage. http://manpages.ubuntu.com/manpages/bionic/man5/machine-id.5.html

> For operating system images which are created once and used on multiple machines, for
       example for containers or in the cloud, /etc/machine-id should be an empty file in the
       generic file system image. An ID will be generated during boot and saved to this file if
       possible. Having an empty file in place is useful because it allows a temporary file to be
       bind-mounted over the real file, in case the image is used read-only.

**Comment by jpalermo** [comment]
Fixed via #155
