### ISSUE TITLE
Outdated debootstrap

### ISSUE THREAD

**Issue by phillc** [cloudfoundry/bosh-linux-stemcell-builder#128]
Hello,

I am trying to build a stemcell for a currently unsupported cloud provider. I was trying to go straight to bionic, since it is newer than xenial.

When I get to the step to run `bundle exec rake stemcell:build_os_image[ubuntu,bionic,$PWD/tmp/ubuntu_base_image.tgz]` I get the error:

```
+ echo 'Running debootstrap'
Running debootstrap
+ debootstrap --arch=amd64 bionic /mnt/stemcells/null/null/ubuntu/work/work/chroot ''
E: No such script: /usr/share/debootstrap/scripts/bionic
```

This is because the debootstrap version declared here: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/stemcell_builder/stages/base_debootstrap/apply.sh#L15 does not support bionic.

In my fork I've removed the lines installing debootstrap, and I have been able to progress.

Do you have any suggestions on how to proceed?

Thanks!

**Comment by voelzmo** [comment]
There is https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master where our work on bionic stemcells happens, this might be a better starting point for you. For example, the specific debootstrap downgrade is removed on this branch: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/fe148f2f18e20757189b2effc39ac2a5bbfcfb93

**Comment by phillc** [comment]
I am progressing with that, thank you.
