### ISSUE TITLE
Need to upgrade glibc to 2.22 or later version

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-linux-stemcell-builder#13]
There needs to upgrade glibc to 2.22 or later version to address the following vulnerability issues:

https://exchange.xforce.ibmcloud.com/vulnerabilities/126597
https://exchange.xforce.ibmcloud.com/vulnerabilities/126596
https://exchange.xforce.ibmcloud.com/vulnerabilities/126595
https://exchange.xforce.ibmcloud.com/vulnerabilities/126591

Any plan to upgrade it? Thanks.

/cc @cppforlife @maximilien

**Comment by dpb587-pivotal** [comment]
Have you verified the stemcells are not patched? It looks like the appropriate patches have already been issued and backported by Canonical to trusty (patches don't necessarily follow the software versions).

**Comment by mattcui** [comment]
@dpb587-pivotal How can I check what patches have been applied for glibc in the stemcell? Thanks.

**Comment by dpb587-pivotal** [comment]
Ubuntu documents the package and release impact of CVEs on their site and have a [CVE Tracker](https://people.canonical.com/~ubuntu-security/cve/) where you can look them up. I was cross-referencing from the X-Force site, but it'd be very helpful and appreciated in the future if you were able to check from the Ubuntu site or provide the generic Ubuntu links.

**Comment by mattcui** [comment]
Thank you @dpb587-pivotal , I checked Ubuntu CVE Tracker, it's DNE for all these CVEs for Ubuntu 14.04. Closing this issue.
