### ISSUE TITLE
Alibaba Cloud Bionic Stemcell missing

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-linux-stemcell-builder#130]
The recently published beta of Bionic Stemcells on bosh.io does not include versions for Alibaba Cloud. This item is intended to start the discussion about how to get it published as well. As far as I know the build pipelines already produce a Bionic heavy stemcell, but there is no validation in place. Can these builds also be published with a corresponding disclaimer to enable others to validate and provide fixes?

**Comment by ramonskie** [comment]
we are now building full stemcells bionic beta stemcells for alicloud.
and are available on bosh.io
https://bosh.io/stemcells/bosh-alicloud-kvm-ubuntu-bionic-go_agent
