### ISSUE TITLE
stemcell ci test failed by step `disables ipv6 in the kernel`

### ISSUE THREAD

**Issue by xiaozhu36** [cloudfoundry/bosh-linux-stemcell-builder#132]
When I running the stemcell CI test and I happened the following error:
```
/tmp/build/87eb1201/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go:73
------------------------------
[Cmd Runner] 2020/11/15 09:58:53 DEBUG - Running command '/usr/local/bin/bosh -n -d stemcell-acceptance-tests --column=stdout ssh default/0 -r -c sudo netstat -lnp | grep sshd | awk '{ print $4 }''
[Cmd Runner] 2020/11/15 09:59:03 DEBUG - Stdout: 0.0.0.0:22	
:::22	
	
[Cmd Runner] 2020/11/15 09:59:03 DEBUG - Stderr: 
[Cmd Runner] 2020/11/15 09:59:03 DEBUG - Successful: true (0)
• Failure [9.392 seconds]
Stemcell [It] #141987897: disables ipv6 in the kernel 
/tmp/build/87eb1201/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go:92

  Expected
      <[]string | len:2, cap:2>: ["0.0.0.0:22\t", ":::22"]
  to equal
      <[]string | len:1, cap:1>: ["0.0.0.0:22"]
```
Is there anyone can help me?

**Comment by StefanWutz** [comment]
I had a look on this issue and it seems that ipv6 is still enabled for vms running bionic stemcells on alicloud.

An ipv6 address is shown for the default nic

```
web/6e626a8c-35d4-467e-b297-26ade1c4467d:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:00:d9:61 brd ff:ff:ff:ff:ff:ff
    inet 10.2.6.0/16 brd 10.2.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe00:d961/64 scope link
       valid_lft forever preferred_lft forever
```

and ipv6 is enabled for sshd :
```
web/6e626a8c-35d4-467e-b297-26ade1c4467d:~# netstat -lnp | grep sshd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3511/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      3511/sshd
```

Interestingly ipv6 is disabled on the system
```
web/6e626a8c-35d4-467e-b297-26ade1c4467d:~# cat /proc/sys/net/ipv6/conf/all/disable_ipv6
1

web/6e626a8c-35d4-467e-b297-26ade1c4467d:~# cat /proc/sys/net/ipv6/conf/default/disable_ipv6
1
```

but this may related to the corresponding settings in cat _/etc/sysctl.d/60-bosh-sysctl.conf_.

```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
```

Validating the behavior on aws I see that ipv6 is disabled.  The only difference I see right now between alicloud and aws is the additional parameter _ipv6.disable=1_ in the file _/etc/default/grub_ on aws.

Can someone confirm that ipv6 is disabled by default?
Should the parameter _ipv6.disable=1_ in the grub configuration set by default for all cloud providers?

**Comment by StefanWutz** [comment]
I have tried to build a custom alicloud stemcell from the ubuntu bionic branch to test the ipv6 issue but I have problems to get a vm up and running.

Bosh complains with the following error message:
```
Task 375 | 12:57:52 | Preparing deployment: Preparing deployment (00:00:00)
Task 375 | 12:57:52 | Preparing deployment: Rendering templates (00:00:00)
Task 375 | 12:57:52 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 375 | 12:57:52 | Creating missing vms: dummy/413b7e4f-6863-4370-986e-16fc598f7d4e (0) (00:11:10)
                    L Error: CPI error 'Bosh::Clouds::CloudError' with message 'update i-gw8f5qx4lw605viqzm2p failed and the vm has been deleted.: change i-gw8f5qx4lw605viqzm2p to Running failed: change instance i-gw8f5qx4lw605viqzm2p to Running timeout' in 'create_vm' CPI method (CPI request ID: 'cpi-539718')
Task 375 | 13:09:02 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'update i-gw8f5qx4lw605viqzm2p failed and the vm has been deleted.: change i-gw8f5qx4lw605viqzm2p to Running failed: change instance i-gw8f5qx4lw605viqzm2p to Running timeout' in 'create_vm' CPI method (CPI request ID: 'cpi-539718')

Task 375 Started  Mon Nov 30 12:57:52 UTC 2020
Task 375 Finished Mon Nov 30 13:09:02 UTC 2020
Task 375 Duration 00:11:10
Task 375 error

Updating deployment:
  Expected task '375' to succeed but state is 'error'

Exit code 1
```

Creating a vm from the uploaded image using the alicloud console does not work too. A message indicated that the resizing of a disk does not work, but I do not found a concrete error log.

I have build the stemcell based on the docker image "ubuntu:bionic" which itself references to the latest tag "ubuntu:bionic-20201119". The docker image introduces a new package "uuid-runtime" which is currently not part of the project. 
Do I need to use a specific ubuntu bionic tag to get a working alicloud image?

Do I need to apply additional steps to change the alicloud image which are not defined inside the bosh-linux-stemcell-builder project?

**Comment by mrosecrance** [comment]
Ipv6 should be [disabled by default](https://www.pivotaltracker.com/n/projects/956238/stories/141987897) for all providers. There's even [a test](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/649c6251ce4407b8737737932c788e967b1a4f07/bosh-stemcell/spec/support/stemcell_shared_examples.rb#L23) for it. I assume you all have seen the unit tests pass already however. 

Note, unit tests are currently failing with the latest bionic image. It looks like a few packages were somewhat unexpectedly bumped (or added). They did pass as recently as Nov 23rd so if you'd rather not wait for a fix to be make, you may be able to pin back. 
```
       -_chrony:x:109:
       -ssh:x:110:
       +uuidd:x:109:
       +_chrony:x:110:
       +ssh:x:111:
```

**Comment by StefanWutz** [comment]
@mrosecrance thank you for the clarification. Indeed the source code looks fine and the unit tests pass. However on a fresh alicloud vm based on bionic stemcell version 0.6 the parameter `ipv6.disable=1` is not set for `GRUB_CMDLINE_LINUX`.

```
worker/fe958d03-16a9-4249-afca-66612a8e8bb1:~$ cat /etc/default/grub
GRUB_CMDLINE_LINUX="vconsole.keymap=us net.ifnames=0 biosdevname=0 crashkernel=auto selinux=0 plymouth.enable=0 console=ttyS0,115200n8 earlyprintk=ttyS0 rootdelay=300  audit=1 cgroup_enable=memory swapaccount=1 console=tty0"
```
Having two blanks between the parameters _rootdelay_ and _audit_ indicates that there is another command removing  `ipv6.disable=1` again.

The other problem arise when testing this behavior with a custom stemcell based on bionic version 0.6 fails due problems booting a vm from the custom alicloud image. I wonder if I have to apply additional repacking scripts to the custom stemcell after it was build?

**Comment by StefanWutz** [comment]
@xiaozhu36 As discussed, can you check that https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=271.2.0#p%3ddirector.ipv6_listen is disabled or not set?

**Comment by xiaozhu36** [comment]
@StefanWutz Ok, thanks, I will have a try.

**Comment by xiaozhu36** [comment]
HI @StefanWutz I happened another error when I test again and the error as following:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest for image 'bosh/main:latest': 429 Too Many Requests
does the image exist?
```
 This error happened in the ci pipeline `update-cloud-config` stage. Do you have any ideas?

**Comment by xiaozhu36** [comment]
HI. @StefanWutz I have tested again with disable commit: https://github.com/aliyun/bosh-deployment/commit/fdc290f85c43e4183fc41eae28a30052ed375677, but it still failed.

**Comment by xiaozhu36** [comment]
Hi @StefanWutz I think the issue results from the PR: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/b1510daa1f8b181fecc65166746190652b14fa6c

The ubuntu bionic stemcell disable the ipv6 by setting `ipv6.disable=1` in the config file `/boot/grub/grub.cfg`. The file `/boot/grub/grub.cfg` automatically generated by grub-mkconfig using templates from /etc/grub.d and settings from /etc/default/grub. 

Although there is a setting in the for `/etc/default/grub`: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/b1510daa1f8b181fecc65166746190652b14fa6c#diff-8da63a2e766804496520b738c5d7c28e18411413674cce1761ad1f50b3542d2dR77 and it contains `ipv6.disable=1`, but it seems like did not take effect in the stemcell, because I logged in the bosh-director and the `/etc/default/grub` content is 
```
$ cat /etc/default/grub 
GRUB_CMDLINE_LINUX="vconsole.keymap=us net.ifnames=0 biosdevname=0 crashkernel=auto selinux=0 plymouth.enable=0 console=ttyS0,115200n8 earlyprintk=ttyS0 rootdelay=300  audit=1 cgroup_enable=memory swapaccount=1 console=tty0"
```
and we can find there is missing `ipv6.disable=1`. It also confused me.

As a check, I added the `ipv6.disable=1` to the end of `GRUB_CMDLINE_LINUX` and then run command `sudo update-grub` and reboot the vm. After that, I found the ipv6 was disabled successfully and the results as following:
```
$ netstat -lnp | grep sshd | awk '{ print $4 }'
0.0.0.0:22
```
So, I think if the stemcell wants to disable ipv6, the grub config should contains `ipv6.disable=1` and it also check in the spec test:  https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-bionic/master/bosh-stemcell/spec/support/stemcell_shared_examples.rb#L23 . I think if the test is valid, there will have a error when building the bionic stemcell. 
I was planning to build a new bionic image to validate my ideas, but I happened another error: 
```
Step 24/30 : ADD ${OVF_TOOL_INSTALLER} /tmp/ovftool_installer.bundle
ADD failed: stat /var/lib/docker/tmp/docker-builder590657892/VMware-ovftool-4.1.0-2459827-lin.x86_64.bundle: no such file or directory
```
If you can build a new custom stemcell, you can validate the idea.

**Comment by ramonskie** [comment]
isse can be closed is this is fixed within the alicloud cpi see https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/issues/122
