### ISSUE TITLE
running stemcell_artifact_test test and got the error

### ISSUE THREAD

**Issue by xiaozhu36** [cloudfoundry/bosh-linux-stemcell-builder#133]
Before I publish a new alibaba cloud bionic light stemcell, I ran the bosh linux stemcell builder ci test, but I happened the following error:
```
• Failure [0.011 seconds]
stemcell.tgz stemcell manifest [It] contains a stemcell manifest 
/tmp/build/87eb1201/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/stemcell_artifact_test.go:60

  Expected
      <int>: 3
  to equal
      <int>: 2
```
It can work when I published the xenial light stemcell.
Is there anyone can give some ideas?

**Comment by StefanWutz** [comment]
Hi @xiaozhu36 ,

can you tell us more about your ci setup?

The error is related to the _api_version_ in the file _stemcell.MF_. The current alicloud stemcell image version 0.6 contains the correct setting `api_version: 3` so the smoke test should pass.

The api version was changed with this commit https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/f4de1ec001c4dd653f24d7ba52efa6a31f139e19#diff-ce639a32ce1636901f646ce57bf74332360a287a2903ca2f0a7e089877c00b24

**Comment by xiaozhu36** [comment]
@StefanWutz My concourse ci pipeline is https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/master/ci/pipeline.yml and please have a check.
By the way, the stemcell.MF comes from the full stemcell.

**Comment by StefanWutz** [comment]
@xiaozhu36 I only see jobs which are related to ubuntu xenial but not to ubuntu bionic. Do you have changes for bionic in a separate branch or do you use the pipeline for xenial and bionic stemcells?

Which branch is used here https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/master/ci/pipeline.yml#L167 for testing?

**Comment by xiaozhu36** [comment]
@StefanWutz I am sorry. It should be in bionic branch: https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/bionic/ci/pipeline.yml. Please check it again. Thanks.

**Comment by StefanWutz** [comment]
@xiaozhu36 I think you should consider to add another resource for the ubuntu-bionic/master branch for building ubuntu bionic stemcells. Right now only master branch is used https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/bionic/ci/pipeline.yml#L632-L636

You are using some external resources https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/bionic/ci/pipeline.yml#L201. To which git project/branch do they belong and are they up to date?

**Comment by xiaozhu36** [comment]
HI @StefanWutz I have switch the bosh-linux-stemcell-builder branch to ubuntu-bionic/master, but the issue also exists.

I did not get your point about `You are using some external resources https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/bionic/ci/pipeline.yml#L201. To which git project/branch do they belong and are they up to date?`. This resource is https://github.com/cloudfoundry-incubator/bosh-cpi-certification and I use the latest master branch. Is there any issue?

**Comment by StefanWutz** [comment]
@xiaozhu36 According to the source https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-bionic/master/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/stemcell_artifact_test.go#L52 the stemcell is defined using an environment variable.
The environment variable is set in the ci pipeline in this task https://github.com/cloudfoundry/bosh-stemcells-ci/blob/master/tasks/test-stemcell.sh#L14.
Can you tell me which stemcell version can be found in this directory?

**Comment by xiaozhu36** [comment]
@StefanWutz I am sorry I can not get your point. What do you mean "which stemcell verison"? This issue happened in the alibaba cloud ubuntu-bionic 0.6: https://bosh.io/stemcells/bosh-alicloud-kvm-ubuntu-bionic-go_agent#v0.6

**Comment by StefanWutz** [comment]
@xiaozhu36 The smoke test extracts and read the file stemcell.MF from the stemcell tgz file which is located under _$(realpath stemcell/*.tgz)_, see  https://github.com/cloudfoundry/bosh-stemcells-ci/blob/master/tasks/test-stemcell.sh#L14.
The stemcell file used for this test scenario may be an old version as it contains the property _'api_version: 2'_. The smoke test itself expects _'api_version: 3'_ and fails.

I extracted the alicloud ubuntu-bionic stemcell version 0.6 and the api_version contains the right version.

**Comment by xiaozhu36** [comment]
@StefanWutz Thanks for your idea. Now, this issue has been fixed by using branch `ubuntu-bionic/master`.
