### ISSUE TITLE
Please revert commit "Flip test for stemcell image having 2 partitions"

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-linux-stemcell-builder#149]
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/e642f0418e61b90ea93f59107e1fd85fd7a58ad1

"exclude_on_softlayer" means other platforms except SoftLayer. So the original test logic is correct. Please revert the commit.

**Comment by jpalermo** [comment]
We were also confused by this logic and reverted the commit. However that broke all the other IAAS stemcell pipelines.

We looked into the rspec tag usage, and `exclude_on_softlayer` should be set to `true` only when building SoftLayer stemcells. 

The reason they are phrased this way is the tags are used for the specs, so `exclude_on_softlayer=true` means skip this test when building SoftLayer.
