### ISSUE TITLE
Update util-linux to 2.27 or later

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh-linux-stemcell-builder#15]
The `logger` command that we use extensively to forward logs from non-syslog-aware components to syslog gained in 2.27 the ability to raise the maximum log line length with the `--size` switch (default 1K). Some of our components love to emit long structured lines and being able to forward them without fragmentation is very important.

In addition, 2.26 also gained the `--id` switch that allows to specify the process ID of the emitting process.

**Comment by dpb587-pivotal** [comment]
We follow Ubuntu's upstream package versions for Trusty, and if it hasn't already been updated, it's not something we should expect to see. Typically, we only see critical bug fixes applied to avoid introducing changes which might affect stability.

This does seem like very useful functionality, but we'll plan on waiting for this in a future Xenial stemcell (it looks like Xenial currently has [2.27.1](https://packages.ubuntu.com/xenial/util-linux)).

**Comment by cppforlife** [comment]
fixed in xenial.
