### ISSUE TITLE
"libreadline.so.6" needed by Postgres is missing from Bionic stemcells

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-linux-stemcell-builder#154]
This issue occurred on bosh director.
stemcell version: Bionic 0.19
bosh release version: 271.7.0

Postgres needs shared library "libreadline.so.6", but it's not installed in Bionic stemcells https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/bf07791506d13aa52d7cd1bfbc78a0c3809f2e9a/bosh-stemcell/spec/assets/dpkg-list-ubuntu-bionic.txt#L286-L288
```
# /var/vcap/packages/postgres-10/bin/psql --version
/var/vcap/packages/postgres-10/bin/psql: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```
```
# ll /lib/x86_64-linux-gnu/libreadline*
lrwxrwxrwx 1 root root     18 Feb  7  2016 /lib/x86_64-linux-gnu/libreadline.so.5 -> libreadline.so.5.2
-rw-r--r-- 1 root root 249144 Feb  7  2016 /lib/x86_64-linux-gnu/libreadline.so.5.2
lrwxrwxrwx 1 root root     18 May 15  2017 /lib/x86_64-linux-gnu/libreadline.so.7 -> libreadline.so.7.0
-rw-r--r-- 1 root root 294632 May 15  2017 /lib/x86_64-linux-gnu/libreadline.so.7.0
```

Is it possible to add `libreadline6` to Bionic stemcells?

**Comment by StefanWutz** [comment]
The library `libreadline6` was completely removed from bionic, see here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877240 and here https://packages.ubuntu.com/search?keywords=libreadline6-dev.

I have tested a bosh director deployment using the internal `postgres-10` job and compilation works fine without referencing to libreadline6 library.

```
:~# /var/vcap/packages/postgres-10/bin/psql --version
psql (PostgreSQL) 10.12
bosh/543b408d-55c2-4b00-ae2d-279edb818ff0:~# ll /lib/x86_64-linux-gnu/libreadline*
lrwxrwxrwx 1 root root     18 Feb  7  2016 /lib/x86_64-linux-gnu/libreadline.so.5 -> libreadline.so.5.2
-rw-r--r-- 1 root root 249144 Feb  7  2016 /lib/x86_64-linux-gnu/libreadline.so.5.2
lrwxrwxrwx 1 root root     18 May 15  2017 /lib/x86_64-linux-gnu/libreadline.so.7 -> libreadline.so.7.0
-rw-r--r-- 1 root root 294632 May 15  2017 /lib/x86_64-linux-gnu/libreadline.so.7.0
:~# /var/vcap/packages/postgres-10/bin/psql --version
psql (PostgreSQL) 10.12
:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

I have tested with bionic version 0.18 and 0.19 and postgresql is working for me.

Can you provide a manifest to verify this issue further? 
Are your compilation vms running on bionic or on xenial?

**Comment by gu-bin** [comment]
Oh, I wrongly used the xenial pre-compiled bosh releases referenced here https://github.com/cloudfoundry/bosh-deployment/blob/bionic-stemcell/bosh.yml#L145 After using the non-compiled bosh release and compiling during the deployment, the issue doesn't exist. Thanks for your time looking into it.
