### ISSUE TITLE
Ubuntu bionic's curl, version 7.58.0, has known bug. Request to upgrade to a higher curl version

### ISSUE THREAD

**Issue by donghoang89** [cloudfoundry/bosh-linux-stemcell-builder#166]
After transition from ubuntu-xenial stemcell (with curl version 7.47.0) to ubuntu-bionic (with curl version 7.58.0). We started running into the following curl issue when using curl to interact with our go application.

`curl: (16) Error in the HTTP2 framing layer`

After a quick investigation, it appears that many other users are having similar issues with curl v7.58.0 as well. An issue has been created on ubuntu bug report page at [https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1833198](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1833198) .

We are looking to have curl version upgraded on the ubuntu-bionic stemcell. Version 7.72.0 appears to be a good candidate. We were able to manually install it on a bosh-deployed vm and use it to interact with our application.

**Comment by ramonskie** [comment]
id rather see this fixed within the ubuntu line it self.
by reopening the bug see https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1833198/comments/4
