### ISSUE TITLE
Update Azure Linux Agent to a newer version

### ISSUE THREAD

**Issue by StefanWutz** [cloudfoundry/bosh-linux-stemcell-builder#170]
Update Azure Linux Agent to a newer version. Switch from python2 to python3 as it is already installed on Bionic stemcell.

**Comment by ramonskie** [comment]
https://github.com/Azure/WALinuxAgent

`stemcel_builder/stages/system_azure_wala/`

**Comment by ramonskie** [comment]
will be added in the new release.
please note that we need to add this in the release notes

**Comment by StefanWutz** [comment]
Fixed in https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/c8715ecd18a9bdf7fb91dd7c8971894602362b8d.
