### ISSUE TITLE
Provide a recipe to build FIPS enabled StemCell based on Ubuntu 'Advantage'  18.04

### ISSUE THREAD

**Issue by transform2cloud** [cloudfoundry/bosh-linux-stemcell-builder#185]
**Unmet need:** Bootable stemcell based on Ubuntu 18.04 which allows FIPS enablement

Through Ubuntu Advantage, a "token" can be obtained to enable the FIPS mode on 18.04. However the recipe to build the stemcell based on such an OS image (for amd64 arch and AWS CPI) is not clearly documented. 
- https://ubuntu.com/security/certifications/docs/fips

**Comment by ramonskie** [comment]
We would gladly accept an PR

currently we do not have any resources for this.
and its not currently on our roadmap. but the cloudfoundry organisation is currently changing and they are now working on technical comity, so i would guess that where this needs be brought up.

i also found a relative comment to your request/FIPS here: https://github.com/cloudfoundry/bosh/issues/2296#issuecomment-787960088
