### ISSUE TITLE
Resizing XFS persistent disks fails with bionic stemcells

### ISSUE THREAD

**Issue by turtschan** [cloudfoundry/bosh-linux-stemcell-builder#195]
Hi there.

Since we switched to bionic stemcells we are having problems with disk resizes of XFS persistent disks. While doing a disk resize we get the following error:

`L Error: Action Failed get_task: Task 95edb65c-3d1d-497c-79c4-b42e036e49de result: Migrating persistent disk: Remounting persistent disk as readonly: Shelling out to mount: Running command: 'mount /dev/vdc1 /var/vcap/store -o ro', stdout: '', stderr: 'mount: /var/vcap/store: /dev/vdc1 already mounted or mount point busy`

So the source disk is unmounted and the remounting as readonly fails. We found the following manual workaround: After a failed disk resize, ssh into the instance and restart `systemd-udevd`, then redeploy with updated manifest. Unfortunately there seems to be no way to automate that for example in the post-stop script since this is to early in the lifecycle. Of course it would be much nicer to fix the actual root cause.

We are currently on OpenStack Queens and we encountered this problem in all bionic GA versions with all current director and OpenStack CPI versions since then. The problem doesn't occur for us with xenial and centos7 stemcells.

Cheers,
Andreas

**Comment by ramonskie** [comment]
which stemcell version are you experiencing this with?
because i want to try and reproduce this error

**Comment by ogrand** [comment]
Hi, I deploy a k8s cluster with openstack cpi v41.

- I ran deployment using `bosh deploy --recreate <target manifest with resizing>` and it went well.
- I noticed that in the error case, there is an additional `umount disk` I did not find with `bosh deploy --recreate` case
```
I, [2021-10-19T00:06:40.942171 #31224] [canary_update(agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9))]  INFO -- DirectorJobRunner: Mounting disk '466372fe-6361-4f0c-b0b9-c19d2fa48d73' for instance 'agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9)'
I, [2021-10-19T00:06:46.966060 #31224] [canary_update(agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9))]  INFO -- DirectorJobRunner: Unmounting disk '466372fe-6361-4f0c-b0b9-c19d2fa48d73' for instance 'agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9)'
I, [2021-10-19T00:06:51.087013 #31224] [canary_update(agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9))]  INFO -- DirectorJobRunner: Detaching disk 466372fe-6361-4f0c-b0b9-c19d2fa48d73
I, [2021-10-19T00:06:59.834581 #31224] [canary_update(agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9))]  INFO -- DirectorJobRunner: Orphaning disk: '466372fe-6361-4f0c-b0b9-c19d2fa48d73', inactive
E, [2021-10-19T00:06:59.841506 #31224] [canary_update(agents/6380d1fa-6e25-4800-b88e-6f1b7fc5dfb5 (9))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 3d68e762-c1d5-4dec-405a-f13ba0c8cbf4 result: Migrating persistent disk: Remounting persistent disk as readonly: Shelling out to mount: Running command: 'mount /dev/vdb1 /var/vcap/store -o ro', stdout: '', stderr: 'mount: /var/vcap/store: /dev/vdb1 already mounted or mount point busy
```
It seems to be the root cause of inability to mount the fs in read-only mode, but didn't explain why...
