### ISSUE TITLE
Orphaned spec files and code

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh-linux-stemcell-builder#226]
It seems like many of the '*_spec.rb' files located in https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell are completely unused, since they do not appear to be included in any of the documented testing commands. This means that the spec examples in such files never get executed.

It seems like **all** of the spec files within that dir are probably orphaned, since none of them appear to be referenced by any of the following code:
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ed5d81325db4cafd89e4feef356b956d13822e06/bosh-stemcell/spec/bosh/stemcell/build_environment_spec.rb#L189
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ed5d81325db4cafd89e4feef356b956d13822e06/bosh-stemcell/lib/bosh/stemcell/build_environment.rb#L58-L63
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ed5d81325db4cafd89e4feef356b956d13822e06/bosh-stemcell/spec/spec_helper.rb#L7

The 3 code blocks above are the only code I found in the repo which would seem to affect/determine which spec files get included in the rspec test suites corresponding to any of the currently-documented test commands/scripts.

The orphaned spec files in the https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell dir include:

- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/archive_filename_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/archive_handler_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/archive_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/build_environment_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/builder_options_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/definition_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/disk_image_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/helpers_sh_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/infrastructure_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/operating_system_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/os_image_builder_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/stage_collection_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/stage_runner_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/stemcell_builder_spec.rb
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-bionic/master/bosh-stemcell/spec/bosh/stemcell/stemcell_packager_spec.rb

Some of those orphaned spec files contain code/examples which seem important, and which should probably still be getting executed as part of the project's documented testing processes.

**Comment by Justin-W** [comment]
It also seems likely that some of the orphaned spec files probably contain examples which may have become broken by commits which occurred after whatever change originally caused the files to become orphaned/ignored. So far, I have been unable to identify the original root cause of the orphaning.

**Comment by rkoster** [comment]
Note to self... test locally and update README
