### ISSUE TITLE
Remove obsolete CI code and update README info

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh-linux-stemcell-builder#227]
Based on [this comment](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/225#issuecomment-1102596607), it seems like the existing README info and code related to the CI process are obsolete? It would be good to have any obsolete CI-related code removed, and the README updated with accurate info about how to properly test via CI.

This issue may also be related to #226?

**Comment by rkoster** [comment]
As discussed during foundational infrastructure working group meeting (should be on youtube) these files are still used. Closing issue
