### ISSUE TITLE
Add a limit to avoid endless bosh-agent setup

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-linux-stemcell-builder#27]
Hi, we occurred a problem as	regards the 'agent' runit service. The problem is the agent process would restart endlessly when running into errors and stuck there. Because the runit service has a fixed auto-restart policy. I knew we need cancel this VM or re-deploy, but I thought we could change the restart policy to stop agent by the setting for runit service such as a retry count or something.

This is a simple '/etc/sv/agent/finish' example to about limiting the bosh-agent start.

```bash
#!/bin/bash
set -e

exit_code=$1
counter_file="./agent_counter"

if [[ ${exit_code} -eq 0 ]]; then
    rm -f ${counter_file}
    exit 0
fi

[[ ! -f "$counter_file" ]] && echo 0 > ${counter_file}

read index < ${counter_file}
if [ ${index} -gt 200 ]; then       # 200 times or more
    rm -f ${counter_file}
    sv stop agent
    exit 0
else
    declare -i tmp=${index}+1
    echo ${tmp} > ${counter_file}
fi

exec sleep 5
```

Thank you. :)

**Comment by dpb587-pivotal** [comment]
Hi - we shouldn't limit the restart policy of the agent. If there are problems within agent, or within director, or network availability which causes an issue with the agent, we should always restart it. We don't want a VM to "disappear" or stop trying to connect to the environment for any reason.

If there's a configuration issue, the expected result would be for it to consistently restart.

Is there a specific issue you were running into that you were trying to solve with this change? We may be able to find a better solution for you.

**Comment by EdwardStudy** [comment]
I don't understand why we need to continue to restart if there's a configuration issue. The agent would restart with wrong settings and jump into same into error endless.

For example, if the agent had an HTTP setting source and got wrong settings, the senseless HTTP requests would be sent and make trouble, especially in large-scale deployment. So I thought stop agent is a remediation to reduce the impact. 


Thank you. :)

**Comment by cppforlife** [comment]
> I don't understand why we need to continue to restart if there's a configuration issue.

it very hard to determine if it's just a configuration issue or somethign else. we've seen countless of times where iaas and its parts somehow end up being flaky hence we want agent to always be ready to restart.

> the senseless HTTP requests would be sent and make trouble, especially in large-scale deployment

what kind of impact are you seeing?

**Comment by EdwardStudy** [comment]
@cppforlife It brought a problem due to a SL restriction on "rate limit" (50 requests per second in one account). We have big accounts which may contain thousands of VMs, if we adopt metadata approach, it's very easy to hit"rata limit exceeded" problem based on the current design in bosh-agent code, and SL also complained there were too many getUserMetadata SL API requests hitting SL endpoint, which even caused the slow response of SL portal.

**Comment by EdwardStudy** [comment]
As I could remember, the agent logs were only kept ten previous rotations. These are another problem to digging the error cause when error logs would be flush.

**Comment by cppforlife** [comment]
> As I could remember, the agent logs were only kept ten previous rotations.

runit logrotates based on a particular size i believe. keeping 10 or so files.

**Comment by mrosecrance** [comment]
Closing as stale.
