### ISSUE TITLE
Version mismatch on rubygems-update

### ISSUE THREAD

**Issue by rthill91** [cloudfoundry/bosh-linux-stemcell-builder#277]
As of the release of rubygems-update 3.4.0 the `install-ruby.sh` fails with the following error

```
+ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.4.5.gem (100%)
ERROR:  Error installing rubygems-update:
        rubygems-update requires Ruby version >= 2.6.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
```

Specifying a version on gem update (`gem update --system 3.3.26`) seems to resolve the issue in testing.

**Comment by ramonskie** [comment]
it seems to me this occurs on the xenial build correct?
as bionic and jammy already uses ruby => 3.1

**Comment by rthill91** [comment]
Yes that's correct, this is seen in a xenial-based pipeline

**Comment by toabctl** [comment]
@ramonskie told me that we should call

```
./run os-image-stemcell-builder-bionic
```
instead of

```
./run os-image-stemcell-builder
```
That latter one is in the top level README. I'll update the readme now to fix this.
