### ISSUE TITLE
Ubuntu Stemcells should perform Duplicate Address Detection according to RFC 5227 and RFC 4862

### ISSUE THREAD

**Issue by Lafunamor** [cloudfoundry/bosh-linux-stemcell-builder#280]
Stemcells should perform Duplicate Address Detection according to [RFC 5227 (IPv4)](https://www.ietf.org/rfc/rfc5227.txt) and [RFC 4862 (IPv6)](https://www.ietf.org/rfc/rfc4862.txt). Not performing this check may lead to unexpected behaviour such as duplicate IP usage and missing or partial connectivity. We discovered that NSX-T is relying on the GARP message sent out after successfully performing the Duplicate Address Detection procedure to update the ARP table of the virtual router. Without the GARP message of the machine we need to rely on the time-out of the ARP table entry which can take up to 10 minutes to be marked as invalid. During this time the machine is not receiving traffic from that router due to the false ARP table entry.
In Ubuntu Jammy, [by default, Duplicate Address Detection is only activated for IPv6 [3]](https://manpages.ubuntu.com/manpages/jammy/man5/systemd.network.5.html#[address]%20section%20options). We should set this to either “both” or IPv4.

Additional Links:
[Slack Discussion](https://app.slack.com/client/T02FL4A1X/C02HPPYQ2/thread/C02HPPYQ2-1675266373.779919)

References:
1. https://www.ietf.org/rfc/rfc5227.txt
2. https://www.ietf.org/rfc/rfc4862.txt
3. https://manpages.ubuntu.com/manpages/jammy/man5/systemd.network.5.html#[address]%20section%20options

**Comment by rkoster** [comment]
Just to provide some more context the bosh director is managing the cleanup of ARP entries through a specific NATS message to all bosh agents. 
- https://github.com/cloudfoundry/bosh-agent/blob/3961b87c28e2af2f20fe0a384646748869ddb0dc/agent/action/delete_arp_entries.go#L38
- https://github.com/cloudfoundry/bosh/blob/42883dbf4bc01471f325ab976b9418f4ddc9d639/src/bosh-director/lib/bosh/director/agent_broadcaster.rb#L16

Could you provide some more details on why this mechanism is not working for you? (I'm assuming it has something to do with NSX-T).

**Comment by Lafunamor** [comment]
Hey @rkoster 
Thanks for pointing me to this. The linked code seems to be related to the [explicit ARP flushing feature of BOSH](https://bosh.io/docs/flush-arp/). I don't think we habe this enabled and I don't think it will help us as a) GARPs will not be sent by Bionic and Jammy stemcells because they are not enabled for IPv4 and b) the problem is on the virtual routing component and not on a BOSH managed VM.

Here is the KB VMware wrote on this case: https://kb.vmware.com/s/article/90777

I'll try to see if enabling explicit ARP flushing will change the behaviour.

**Comment by rkoster** [comment]
The command documented in the workaround section of the KB article is being run bosh-bosh agent: https://github.com/cloudfoundry/bosh-agent/blob/3961b87c28e2af2f20fe0a384646748869ddb0dc/platform/net/arp/arping.go#L100
It will be executed once the agent finishes setting up the network interfaces: https://github.com/cloudfoundry/bosh-agent/blob/3961b87c28e2af2f20fe0a384646748869ddb0dc/platform/net/ubuntu_net_manager.go#L193

**Comment by Lafunamor** [comment]
I found the reason why this is not working as we'd expect:
We're using a DNS name for BOSH and this DNS name cannot be resolved before connectivity is set up. The ARPing is sent after configuring the NATS firewall, which fails due to the failing connectivity.
`ERROR - App setup Running bootstrap: Setting up networking: Setting up nats firewall: Error resolving mbus host: <DNS-name-redacted>: lookup <DNS-name-redacted> on <DNS-server-ip>:53: read udp <ip>:58224-><ip>:53: i/o timeout`
With Ubuntu Kinetic the arping behaviour should actually be covered by the OS.

**Comment by Lafunamor** [comment]
resolved in ubuntu-bionic/1.181 which includes above PR
