### ISSUE TITLE
Unable to create VM for ubuntu-bionic-stemcell after v1.150

### ISSUE THREAD

**Issue by tsato1222** [cloudfoundry/bosh-linux-stemcell-builder#282]
## Overview

Unable to create VM for ubuntu-bionic-stemcell after v1.150.
To be precise, the VM itself can be created, but the bosh agents that are supposed to run inside the VM fail to start,   
and through them the VM is destroyed.

Note, the execution environment is Azure, so I use bosh-azure-hyperv-ubuntu-bionic-go_agent.

## To Reproduce

Run the command to create VM for ubuntu-bionic-stemcell v1.150.
In my case, it happened when running export-release.

```
bosh -e bosh -d compilation export-release --dir ./export-releases xxxxx/x.x ubuntu-bionic/1.150

...

Task 233400

Task 233400 | 03:51:29 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 233400 | 03:51:29 | Compiling packages: xxxx/xxxxxx
Task 233400 | 03:51:29 | Compiling packages: xxxx/xxxxxx (00:12:43)
                      L Error: Timed out pinging to xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx after 600 seconds

Task 233400 Started  Wed Feb 15 03:51:29 UTC 2023
Task 233400 Finished Wed Feb 15 04:04:45 UTC 2023
Task 233400 Duration 00:13:16
Task 233400 error
```

In the VM created during command execution, bosh-agent failed to start and the following log was output.

```
# /var/vcap/bosh/bin/bosh-agent -P ubuntu -C /var/vcap/bosh/agent.json
[main] 2023/02/15 03:55:48 DEBUG - Starting agent
[File System] 2023/02/15 03:55:48 DEBUG - Reading file /var/vcap/bosh/agent.json
[File System] 2023/02/15 03:55:48 DEBUG - Read content
********************
{
  "Platform": {
    "Linux": {
      "CreatePartitionIfNoEphemeralDisk": true,
      "DevicePathResolutionType": "scsi",
      "PartitionerType": "parted" 
    }
  },
  "Infrastructure": {
    "Settings": {
      "Sources": [
        {
          "Type": "ConfigDrive",
          "DiskPaths": [
            "/dev/disk/by-label/azure_cfg_dsk",
            "/dev/disk/by-label/AZURE_CFG_DSK" 
          ],
          "MetaDataPath": "configs/MetaData",
          "UserDataPath": "configs/UserData" 
        },
        {
          "Type": "File",
          "MetaDataPath": "",
          "UserDataPath": "/var/lib/waagent/CustomData",
          "SettingsPath": "/var/lib/waagent/CustomData" 
        }
      ],
      "UseServerName": true,
      "UseRegistry": true
    }
  }
}

********************
[File System] 2023/02/15 03:55:48 DEBUG - Reading file /var/vcap/bosh/etc/stemcell_version
[File System] 2023/02/15 03:55:48 DEBUG - Read content
********************
1.150
********************
[File System] 2023/02/15 03:55:48 DEBUG - Reading file /var/vcap/bosh/etc/stemcell_git_sha1
[File System] 2023/02/15 03:55:48 DEBUG - Read content
********************
28c35ab824b069327f0d9495044977627651d869+
********************
[App] 2023/02/15 03:55:48 INFO - Running on stemcell version '1.150' (git: 28c35ab824b069327f0d9495044977627651d869+)
[File System] 2023/02/15 03:55:48 DEBUG - Checking if file exists /var/vcap/bosh/agent_state.json
[File System] 2023/02/15 03:55:48 DEBUG - Stat '/var/vcap/bosh/agent_state.json'
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Running command 'bosh-agent-rc'
[unlimitedRetryStrategy] 2023/02/15 03:55:48 DEBUG - Making attempt #0
[DelayedAuditLogger] 2023/02/15 03:55:48 DEBUG - Starting logging to syslog...
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stdout: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stderr: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Successful: true (0)
[File System] 2023/02/15 03:55:48 DEBUG - Checking if file exists /dev/disk/by-label/azure_cfg_dsk
[File System] 2023/02/15 03:55:48 DEBUG - Stat '/dev/disk/by-label/azure_cfg_dsk'
[ConfigDriveSettingsSource] 2023/02/15 03:55:48 WARN - Failed to load config from /dev/disk/by-label/azure_cfg_dsk - Failed to get file contents, disk path '/dev/disk/by-label/azure_cfg_dsk' does not exist
[File System] 2023/02/15 03:55:48 DEBUG - Checking if file exists /dev/disk/by-label/AZURE_CFG_DSK
[File System] 2023/02/15 03:55:48 DEBUG - Stat '/dev/disk/by-label/AZURE_CFG_DSK'
[ConfigDriveSettingsSource] 2023/02/15 03:55:48 WARN - Failed to load config from /dev/disk/by-label/AZURE_CFG_DSK - Failed to get file contents, disk path '/dev/disk/by-label/AZURE_CFG_DSK' does not exist
[settingsService] 2023/02/15 03:55:48 DEBUG - Loading settings from fetcher
[File System] 2023/02/15 03:55:48 DEBUG - Checking if file exists /dev/disk/by-label/azure_cfg_dsk
[File System] 2023/02/15 03:55:48 DEBUG - Stat '/dev/disk/by-label/azure_cfg_dsk'
[ConfigDriveSettingsSource] 2023/02/15 03:55:48 WARN - Failed to load config from /dev/disk/by-label/azure_cfg_dsk - Failed to get file contents, disk path '/dev/disk/by-label/azure_cfg_dsk' does not exist
[File System] 2023/02/15 03:55:48 DEBUG - Checking if file exists /dev/disk/by-label/AZURE_CFG_DSK
[File System] 2023/02/15 03:55:48 DEBUG - Stat '/dev/disk/by-label/AZURE_CFG_DSK'
[ConfigDriveSettingsSource] 2023/02/15 03:55:48 WARN - Failed to load config from /dev/disk/by-label/AZURE_CFG_DSK - Failed to get file contents, disk path '/dev/disk/by-label/AZURE_CFG_DSK' does not exist
[settingsService] 2023/02/15 03:55:48 DEBUG - Successfully received settings from fetcher
[File System] 2023/02/15 03:55:48 DEBUG - Checking if file exists /var/vcap/bosh/update_settings.json
[File System] 2023/02/15 03:55:48 DEBUG - Stat '/var/vcap/bosh/update_settings.json'
[File System] 2023/02/15 03:55:48 DEBUG - Making dir /var/vcap/bosh with perm 0777
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Running command 'usermod -p * root'
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stdout: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stderr: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Successful: true (0)
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Running command 'usermod -p * vcap'
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stdout: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stderr: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Successful: true (0)
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Running command 'hostname '
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stdout: 
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Stderr: hostname: the specified hostname is invalid
[Cmd Runner] 2023/02/15 03:55:48 DEBUG - Successful: false (1)
[main] 2023/02/15 03:55:48 ERROR - App setup Running bootstrap: Setting up hostname: Setting hostname: Running command: 'hostname ', stdout: '', stderr: 'hostname: the specified hostname is invalid
': exit status 1
```

**Comment by ramonskie** [comment]
i have checked for any changes that could be related to azure from 1.140x till now a
and could not find changes that would affect azure stemcells.

it seems to me that the azure agent could not contact the metadata server to retrieve the proper information.
will investigate further

**Comment by ramonskie** [comment]
it could be related to https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/678

**Comment by beyhan** [comment]
@tsato1222 can you provide information about what changed in your env? Was it only a stemcell update with the same Azure CPI version and same director version? Does bosh tries to create multiple VMs at once and only some of them fail or all VM create operations fail?

**Comment by tsato1222** [comment]
Yes, only the version of stemcell has changed, nothing has changed in the bosh director version/settings.

Versions prior to bionic v1.145 can be created with no problem.

In my case, I did not instruct the process to create multiple VMs, I tried to create 1VM specifying a v1.150 stemcell and it failed.

**Comment by rkoster** [comment]
It seems like the agent id is empty, which is passed to the `hostname` command here:
https://github.com/cloudfoundry/bosh-agent/blob/945665858eb59c973e1a8a3feb7d36d0e0d23826/platform/linux_platform.go#L523

and here: https://github.com/cloudfoundry/bosh-agent/blob/945665858eb59c973e1a8a3feb7d36d0e0d23826/agent/bootstrap.go#L94

Could you check the contents of: `/var/lib/waagent/CustomData` to make sure there is an agent id?

**Comment by tsato1222** [comment]
`/var/lib/waagent/CustomData` is as follows.

```
/:~# cat /var/lib/waagent/CustomData 
{"registry":{"endpoint":"http://registry:xx.xx.xx.xx@xx.xx.xx.xx:25777"},"server":{"name":"agent_id:b983d680-d4f2-4281-80b3-1653b389dd11;resource_group_name:xxxxxxxx;storage_account_name:xxxxxxxx"},"dns":{"nameserver":["xx.xx.xx.xx","xx.xx.xx.xx","xx.xx.xx.xx","xx.xx.xx.xx"]}}
```

**Comment by rkoster** [comment]
Could you also provide `/var/lib/cloud/instance/user-data.txt` and could you also get a copy of these files on a working instance?

**Comment by tsato1222** [comment]
@rkoster 
I checked, but there is no /var/lib/cloud to begin with.

**Comment by tsato1222** [comment]
I found out as a result of my research.

- The `agent_state.json`  in the v1.145 VM was not found in the v1.150 VM. So I put the following file in `/var/vcap/bosh`, the hostname error is avoided.
   ```
   echo '{"Linux":{"hosts_configured":true}}' > /var/vcap/bosh/agent_state.json
   ```

- The next time, I re-ran the bosh-agent startup, I got an error indicating that disk space is low.   
   By default, `root_disk` seems to be 3GiB, but it no longer seems to be enough.   
   This error was avoided by setting `root_disk` in `cloud_properties` to a value greater than 3GiB.
   https://bosh.io/docs/azure-cpi/#resource-pools

-  I tried to start bosh-agent again and got the following error message. The error message states that there is no `bosh-blobstore-` executable in the PATH.   
   However, I do not know why this is the case, since `bosh-blobstore-dav` is actually in `/var/vcap/bosh/bin/` .
   ```
   ********************
   vcap:random-password
   ********************
   [File System] 2023/03/07 09:26:13 DEBUG - Symlinking oldPath /etc/sv/monit with newPath /etc/service/monit
   [File System] 2023/03/07 09:26:13 DEBUG - Lstat '/etc/service/monit'
   [attemptRetryStrategy] 2023/03/07 09:26:13 DEBUG - Making attempt #0 for *platform.monitRetryable
   [Cmd Runner] 2023/03/07 09:26:13 DEBUG - Running command 'sv start monit'
   [Cmd Runner] 2023/03/07 09:26:13 DEBUG - Stdout: ok: run: monit: (pid 4244) 469s, normally down
   [Cmd Runner] 2023/03/07 09:26:13 DEBUG - Stderr: 
   [Cmd Runner] 2023/03/07 09:26:13 DEBUG - Successful: true (0)
   [main] 2023/03/07 09:26:13 ERROR - App setup Getting blobstore: Getting blobstore: Validating blobstore: executable bosh-blobstore- not found in PATH
   [main] 2023/03/07 09:26:13 ERROR - Agent exited with error: Getting blobstore: Getting blobstore: Validating blobstore: executable bosh-blobstore- not found in PATH
   ```

**Comment by tsato1222** [comment]
I rebuilt stemcell with the version of bosh-agent v2.471.0 in bionic v1.181 and the VM was created without problems.
The bosh-agent v2.471.0 is the version included in bionic v1.145.
Thus, the current workaround is to rebuild with a lower version of bosh-agent.

I hope this information will help to resolve the stemcell issue as soon as possible.

**Comment by beyhan** [comment]
For reference [these](https://github.com/cloudfoundry/bosh-agent/compare/v2.471.0...v2.514.0) are the changes in the bosh-agent from `v2.471.0` to `v2.514.0`. I don't see anything suspicious in the changes, which could be the root cause for this issue.

**Comment by tsato1222** [comment]
I would appreciate it if someone could create a stemcell on Azure to see if the same problem occurs in order to find the cause.

**Comment by ramonskie** [comment]
if as you say an older agent version works with a newer stemcell.
it could be maby related to this PR. although i cannot find anything at first glance https://github.com/cloudfoundry/bosh-agent/pull/287

also we first need to be able to replicate this issue.

and i wonder if you have the same issues with a jammy stemcell?
as bionic is EOL in april

**Comment by tsato1222** [comment]
`and i wonder if you have the same issues with a jammy stemcell?`
Yes.

**Comment by rkoster** [comment]
Would you be able to narrow down the agent version which broke? Given that `v2.471.0 to v2.514.0` is quite a big diff. For example does it work with `v2.472.0`?

**Comment by rkoster** [comment]
Could this be related to: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/285

**Comment by tsato1222** [comment]
Since it worked in bionic-stemcell v1.145 and not in v1.150.
So I think the difference between bosh-agent `v2.471` - `v2.479` has an effect.
I have not been able to identify it further.

Also in Ubuntu Jammy, even if downgraded to bosh-agent `v2.471`,
It does not work, probably because of the different structure of `agent.json`.
In this case, I think the following commits are affected
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/57081728e5ae295ef69e546ac97db81dbc7f2fbb

In my environment, I downgraded bosh-agent and modified it to undo the above commit, and it works.

**Comment by rkoster** [comment]
Are these issues only happening during compilation asking because of:
```
Task 233400 | 03:51:29 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 233400 | 03:51:29 | Compiling packages: xxxx/xxxxxx
Task 233400 | 03:51:29 | Compiling packages: xxxx/xxxxxx (00:12:43)
                      L Error: Timed out pinging to xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx after 600 seconds
```
Also is it happening for all packages? or are only some packages affected?

**Comment by tsato1222** [comment]
This occurs in all packages because the bosh-agent, which is required for any process, fail to start.

**Comment by rkoster** [comment]
Do you still have the same issue with the 1.195 stemcell?

**Comment by ivo4311** [comment]
I had a chance to spin up a fresh [bosh deployment](https://github.com/cloudfoundry/bosh-deployment) on Azure using the latest version and the jammy stemcell (1.105) and everything was working fine. My test deployment was successful and I could successfully export releases from it using the default stemcell.

@tsato1222  Can you confirm this is still an issue on jammy as well? There have been a lot of commits since the days of 1.150 bionic and it seems this might have been fixed along the way.

**Comment by tsato1222** [comment]
Thank you for letting me know that it is working properly. It will be a little late, but I will check if it works fine in my environment.

**Comment by rkoster** [comment]
Please let us know if it worked.

**Comment by tsato1222** [comment]
Unfortunately, the situation did not change.
I wonder if the version of bosh director has an effect? I am using a very old version in my environment, could this have anything to do with this error?

**Comment by ramonskie** [comment]
it would be weird. but it could be

**Comment by tsato1222** [comment]
ok, if it works fine in Azure, then it may be a problem specific to my environment. Fortunately there is the workaround, so I will close this issue once. If anyone encounters the same error again, please reopen this issue.
