### ISSUE TITLE
Install rsyslog packages from ubuntu apt repository

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh-linux-stemcell-builder#299]
[Currently](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ddf0ab828d7f21becf3527bc71077246d92fe6f1/stemcell_builder/stages/base_ubuntu_packages/apply.sh#L56) we install rsyslog packages from a PPA.

It would be more consistent if we could install these from the default Ubuntu apt repository. We tried removing these during Jammy building but not all the rsyslog plugin packages were available.

See which packages are missing, and how important those packages are.

**Comment by bgandon** [comment]
Some context about this, I remember the `rsyslog-mmnormalize` module being added in 2021 “_for better filtering_” through this PR from SAP: #189

Also possibly releavant, this commit from 2018 that re-enabled the rsyslog PPA: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/840bb291cbc7e596f5e6d409a0b24bd90ba0a12d
Pivotal tracker story gives insights: https://www.pivotaltracker.com/n/projects/956238/stories/159533409

The `rsyslog-mmjsonparse` package seems to have appeared in March 2025, during the CentOS 7 Stemcell work: https://github.com/cloudfoundry/bosh/commit/1c0852b05f85d60f3902e5fab0cb84ea3c0ee67a
_(Before that, Rsyslog was built from source with the `json-c` library for CentOS 6.5.)_

Later on in April 2015, the `rsyslog-mmjsonparse` package has been added to Ubuntu Trusty in this commit: https://github.com/cloudfoundry/bosh/commit/ed561bb2c6df3a84cd3c08701609ce2693554a5d

**Comment by ramonskie** [comment]
we could also move to syslog-ng
see https://www.syslog-ng.com/products/open-source-log-management/syslog-ng-rsyslog-comparison.aspx

**Comment by ramonskie** [comment]
slack communication https://cloudfoundry.slack.com/archives/C06HTDT78N9/p1710346873390969

**Comment by ramonskie** [comment]
https://github.com/rsyslog/rsyslog-pkg-ubuntu/issues/168

**Comment by ramonskie** [comment]
we will remove the adiscon ppa and use the default rsyslog.
as the need for the additional  addons is not needed anymore

**Comment by ramonskie** [comment]
can be closed as #387 will only remove commented out adiscon repo anyway
