### ISSUE TITLE
AWS AMI is missing from cn-north-1 region after released in about a month time

### ISSUE THREAD

**Issue by garyliu-philips** [cloudfoundry/bosh-linux-stemcell-builder#304]
Hi,

We are using this [stemcell](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-jammy%2Fv1.260) which was released in Oct 12. However, we encountered an error 
```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'Stemcell does not contain an AMI in region cn-north-1' in 'create_stemcell' CPI method
```
and we noticed the respective AWS AMI `ami-05d0602bfa002d885` was missing from the `cn-north-1` region. We also noticed any other previous AMI has disappeared.

Can someone please shed some lights regarding:
1. When v1.260 stemcell AMI was removed? Was this only removed from `cn-north-1` AWS region?
2. Is there a house cleaning practice in place to remove AMI? What is the schedule and affected regions in this case?

Cheers,
Gary

**Comment by garyliu-philips** [comment]
please excuse me if this is not the right place to raise this concern and please suggest which repo is the owner of these stemcells

**Comment by jpalermo** [comment]
Sorry about that. We had some problems with the AWS account that hosts these stemcells. The account is active again, but we are having trouble getting the previous stemcells marked as "public" again.

We've had a support ticket open with AWS for a couple of weeks, but they haven't been able to resolve the issue yet.

For now, you can use the heavy version of the stemcell, or use stemcells released after 2023/10/25 (new stemcells are not a problem, only the older ones seem to have a problem getting marked as "public").

We're continuing to work with AWS to get the old stemcell AMIs marked as public though.

**Comment by jpalermo** [comment]
AWS has resolved the issue and we were able to make all the Stemcell AMIs public again. Let us know if you have any more problems with them.
