### ISSUE TITLE
Resize of persistent disks fails on recent Jammy stemcells - systemd mount namespacing issue?

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/bosh-linux-stemcell-builder#310]
We are experiencing the same symptoms as https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/195

Namely, resize of a persistent disk is failing with message:

```
Remounting persistent disk as readonly: Shelling out to mount: Running command: 'mount /dev/sdc1 /var/vcap/store -o ro', stdout: '', stderr: 'mount: /var/vcap/store: /dev/sdc1 already mounted or mount point busy
```

This is using the following vSphere stemcell: `bosh-vsphere-esxi-ubuntu-jammy-go_agent/1.329`

Outside of a resize operation, we can reproduce this on a BOSH VM by SSHing to it, and, in a root shell, running the commands:

```bash
# restart either auditd or chronyd
service auditd restart

# stop all bosh services
monit stop all
sleep 10 # or wait for all services to stop

# unmount persistent disk
umount /var/vcap/store

# try to remount it
mount /dev/sdc1 /var/vcap/store -o ro
# Output (ERROR):
# mount: /var/vcap/store: /dev/sdc1 already mounted or mount point busy.

# CLEANUP:
# mount as read-write - this will succeed
mount /dev/sdc1 /var/vcap/store
monit start all
```

(credit to @bg-govau for finding the above steps)

A more generic way to reproduce this, that does not require stopping BOSH services or messing with the real persistent disk, is as follows:

```bash
# create a temp file for our block device
tmpfile=$(mktemp)

# needs to be a decent size to format as XFS
truncate -s 50M "${tmpfile}"

# make a loop devices that points to this file
loopdev="$(losetup --find --show "${tmpfile}")"

# format it as XFS
mkfs -t xfs "${loopdev}"

# make somewhere to mount it
mntdir="$(mktemp -d)"

# mount it as read-write
mount "${loopdev}" "${mntdir}"

# restart auditd
service auditd restart

# now unmount it
umount "${mntdir}"

# now try to re-mount it, but as read-only (rw will work)
mount "${loopdev}" "${mntdir}" -o ro
# Output (ERROR):
# mount: /tmp/tmp.PMLRvWX6wP: /dev/loop0 already mounted or mount point busy.

# CLEANUP:
service auditd restart
losetup --detach "${loopdev}"
rmdir "${mntdir}"
rm "${tmpfile}"
```

However try as I may, I am *unable* to reproduce that 2nd method on an AWS standard Ubuntu Jammy VM - and I can't tell why! But it does happen every time on our stemcells, hence raising the issue here (rather than with `systemd`).

Here's what we've noted so far:

# `auditd` and `chronyd` have their own `mount_namespace`

If we run `pstree -S` we see that some services started by `systemd` have their own `mnt` (mount) namespace:

```
systemd─┬─VGAuthService
        ├─agetty
        ├─auditd(mnt)─┬─audisp-syslog
        │             └─2*[{auditd}]
        ├─chronyd(mnt,uts)───chronyd
        ├─cron
        ├─dbus-daemon
        ├─networkd-dispat
        ├─rsyslogd───10*[{rsyslogd}]
        ├─runsvdir─┬─runsv─┬─bosh-agent───11*[{bosh-agent}]
        │          │       └─svlogd
        │          └─runsv─┬─monit-actual───{monit-actual}
        │                  └─svlogd
        ├─sshd───sshd───sshd───bash───sudo───bash───pstree
        ├─systemd───(sd-pam)
        ├─systemd-journal
        ├─systemd-logind(mnt,uts)
        ├─systemd-network(mnt)
        ├─systemd-udevd(mnt,uts)
        └─vmtoolsd───3*[{vmtoolsd}]
```

# Mount propagation does not appear to be working properly

If these services are started *before* the persistent disk is mounted, then there are no issues. However if they are restarted *after* `/var/vcap/store` is mounted, then they can see those, and can continue to see those after the device is unmounted.

For example:

```
monit stop all
# wait for all to stop

# restart auditd to demonstrate the issue
service auditd restart

# verify it is currently mounted:
ls -l /var/vcap/store
# Output:
# total 0
# drwxrwxr-x 3 vcap vcap 18 Sep 28 01:23 mongod
# drwxr-xr-x 2 root root  6 Sep 28 01:23 mongodb_exporter
# drwxr-xr-x 2 root root  6 Sep 28 01:23 node_exporter

# unmount it
umount /var/vcap/store

# try to mount as read-only
mount /dev/sdc1 /var/vcap/store -o ro
# Output: 
# mount: /var/vcap/store: /dev/sdc1 already mounted or mount point busy.

# verify that it isn't mounted:
ls -l /var/vcap/store
# Output:
# total 0

# use nsenter to demonstrate that `auditd` still sees this as mounted in its own namespace:
nsenter --target $(cat /run/auditd.pid) --all ls -l /var/vcap/store
# Output:
# total 0
# drwxrwxr-x 3 vcap vcap 18 Sep 28 01:23 mongod
# drwxr-xr-x 2 root root  6 Sep 28 01:23 mongodb_exporter
# drwxr-xr-x 2 root root  6 Sep 28 01:23 node_exporter

# restart auditd again, it now forgets about the old mount
service auditd restart

# and we can now successfully mount it as read-only
mount /dev/sdc1 /var/vcap/store -o ro
```

And this explain why we are affected. One of our BOSH jobs has a pre-start script which modifies the `auditd` config, and restarts it.

# The `systemd` documentation is really confusing

The configuration for `auditd` (which is standard) includes:

```
### Security Settings ###
MemoryDenyWriteExecute=true
LockPersonality=true
ProtectControlGroups=true
ProtectKernelModules=true
ProtectHome=true
RestrictRealtime=true
```

See <https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html> for docs on these, some of which imply that those options will disable mount propagation.

If we comment them all out, then the issue clears up. And interestingly upstream `auditd` has removed some of these (2 years ago!) but those are not backported into Jammy.

However this isn't the full story. If we create a VM in AWS, using their standard Jammy image (`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207`), and run those same reproduction steps above (the generic version), the mount propagation *does* work as expected (`umount` in host propagates into slave `auditd` process).

Therefore I suspect that this should work with the standard security options, however perhaps something else in the stemcell is undoing this?

# What is different between the vSphere stemcell and the AWS Jammy image?

Not much as far as I can tell. The versions of `auditd` and `systemd` are the same.

When I print out all config options `systemctl show --all` the only difference I noted that looked significant is that the BOSH one shows:

```
Tainted=cgroupsv1
```

And AWS did not. This felt like a solid lead, and I found:

https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/c3e6a15dc4e0a9d2ae65b871947a53bf1801b0ac/stemcell_builder/stages/image_install_grub/apply.sh#L87-L89

I tried setting the same in my AWS VM and restarted. After doing so it also showed `Tainted=cgroupsv1` however the issue still wouldn't reproduce.

I can't easily rebuild the stemcell (without this setting) to test from the other direction.

What I have noted is that the output of `mountinfo` differs on each system. On the vSphere BOSH system we see:

```bash
cat /proc/$(cat /run/auditd.pid)/mountinfo | grep "${loopdev}"

# Output:
# 475 474 7:0 / /tmp/tmp.3V7N9qPucV rw,relatime shared:211 - xfs /dev/loop0 rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
```

And on AWS Jammy:

```bash
cat /proc/$(cat /run/auditd.pid)/mountinfo | grep "${loopdev}"

# Output:
# 524 194 7:8 / /tmp/tmp.jAtl1twL1v rw,relatime shared:337 master:346 - xfs /dev/loop8 rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
```

Note that vSphere shows: `shared:211` and AWS shows `shared:337 master:346`.

I think that means the AWS one will receive updates from `master:346` whereas the vSphere one will not receive updates from anything - and I think that matches what we are seeing. However I can't pick where the `systemd` config differs.

And that's as far as we've got. Does anyone have an idea what is going on to make our systemd behave differently to the AWS Jammy one?

**Comment by ghost** [comment]
I found [this thread](https://systemd-devel.freedesktop.narkive.com/GvCyZM4Z/changing-the-mount-make-shared-default) on the internet which describes how to restore `systemd` to the default before [their change](https://github.com/systemd/systemd/commit/b3ac5f8cb98757416d8660023d6564a7c411f0a0) (12 years ago).

On a hunch, I ran `grep -r private /etc` on the BOSH VM, and sure enough, found this file:
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/914b37862104cad6b49b3630be4570c90ef6be20#diff-60e3485cb060306454b1646b6184caeaf2390bd16907601ce9b4bedbb98a5591

From the commit comment (6 years ago):

> Remount root drive as rprivate
> Systemd will make / shared by default, this is different than what we
> had on trusty and breaks some of the garden interactions with containers
> and mounts.
> 
> We chose to revert back to rprivate since that avoids having to make too
> many changes too several different projects.
> 
> [#153888006](https://www.pivotaltracker.com/story/show/153888006)
> 
> Signed-off-by: Chris Dutra <cdutra@pivotal.io>

And the linked tracker says:

> it appears that bosh-warden-cpi-release fails with mysterious mounting problem: https://github.com/cppforlife/bosh-warden-cpi-release/issues/14. host vm was on a xenial stemcell. container is on trusty warden stemcell.
>
> timebox to several hours.

The [linked issue](https://github.com/cloudfoundry/bosh-warden-cpi-release/issues/14) in `bosh-warden-cpi-release` may in fact have been fixed in https://github.com/cloudfoundry/bosh-warden-cpi-release/pull/13

And sure enough, if I delete that file, restart the BOSH VM, then my test-cases above both succeed, and outputs match what see on AWS.

Can we consider reverting (for Jammy) that change from 7 years ago (which was copied from the Bionic -> Xenial -> Jammy code) away from the default that `systemd` uses on a standard VM? 

Related issues this may resolve:
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/195
https://github.com/cloudfoundry/bosh-agent/issues/252 (matches many of the same keywords not sure if solved with this)

**Comment by bgandon** [comment]
What you’ve found is great 👍 Just a few comments:

- I’ve worked on cloudfoundry/bosh-agent#252 and it’s unrelated to this issue.
- I remember #195 and definitely thinks there might be a relation indeed.
- For some years, the resizing persistent disks in [Bosh-lite](https://bosh.io/docs/bosh-lite/) is broken with some obscure “_can’t remount because device is busy_” issue, which might very well be related to this.
- For some months, Concourse in Bosh-lite is having obscure issues with volume management that block nearly all task executions, which might also be related to this.

I’ll try to validate some of the assumptions above, but the investigations you’ve done are fantastic. In the process to solve the issues above, understanding the mount propagation concept and the mount namespace inheritance tree is a huge step forward. 👏
