### ISSUE TITLE
Stemcell building on M1/M2 laptops was removed in readme file

### ISSUE THREAD

**Issue by Malsourie** [cloudfoundry/bosh-linux-stemcell-builder#316]
Hi,
I realised that the documentation about the building stemcell on M-chip Mac, which was introduced in commit https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/d42472facb92b10c9eb89d435d86586135c89092, was deleted in the recent commit https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/7316288f99708625ff01bdcb86220e4eca26db0a. May I ask for the reason and whether there is still solution to build the stemcell on a Arm-based computer?

**Comment by cunnie** [comment]
Sorry @Malsourie , I removed the instructions because I couldn't get them to work, so I finally gave up. But feel empowered: if you can make it work, please submit a PR with these instructions. I'd find that very helpful!
