### ISSUE TITLE
Noble uses EFI (extensible firmware interface) not MBR (Master Boot Record)

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-linux-stemcell-builder#321]
- Requires a "boot" partition, "/boot/efi:
- must be partition type fat32, formatted as vfat, needs at least 6MB, 30MB should be enough
- typically /dev/sda1; root partition migrates to /dev/sda2.
- Enables certain features, such as accessing GPUs w/ > 16 GiB RAM

**Comment by ramonskie** [comment]
added efi support for aws,gcp,vsphere with the following commits
- e8d1cce201064731d34c514fb038b0df246dfde4
- 696e13392fc8f6fe0fe525745e6fa9a6cbd5763c
- a7adae7bb41eb60c50b2b9f22f31fddf7a4f947a
