### ISSUE TITLE
Noble Numbat stemcell no longer uses `runit` to launch the agent

### ISSUE THREAD

**Issue by aramprice** [cloudfoundry/bosh-linux-stemcell-builder#322]
Currently the `bosh-agent` is started [using a separate process manager `runit`](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-jammy/master/stemcell_builder/stages/bosh_go_agent/apply.sh).

This issue proposed removing `runit` in favor of the existing process manager on Ubuntu, `systemd`.

Having a single process management system allows that system to optimize startup across all processes in the system hopefully speeding up the time-to-ready for the whole system.

This is related to though not dependent on [replacing `monit`](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/320) (also with `systemd`).

**Comment by ramonskie** [comment]
when moving the agent and monit to systemd.
i noticed that `chpst` is used in almost all bosh releases which will run a program with the user vcap
`chpst` is a component from runit. so we still need to have runit.
there is an option to replace it  `chpst -u vcap:vcap` with:

- `runuser- u vcap -g vcap executable`
- `systemd-run --uid vcap --guid vcap`
- `setpriv--reuid vcap --regid vcap`

**Comment by rkoster** [comment]
As discovered by Ramon: the agent also invokes runit directly to start monit: https://github.com/cloudfoundry/bosh-agent/blob/main/platform/monit_retryable.go#L20
This should become configurable similar to: https://github.com/cloudfoundry/bosh-agent/pull/324

**Comment by jpalermo** [comment]
We should consider what we want to do with bosh-lite too. We could keep `runit` just on the warden stemcells or we could come up with an alternative (since systemd doesn't run under warden stemcells)

**Comment by ramonskie** [comment]
in the meantime i have removed the runit units for monit and the agent and converted them to systemd services
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/c27910fdf1ee48187ae767edb27df3f5d666b17b

**Comment by beyhan** [comment]
This is still open because of https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/352. Or @ramonskie is there anything else open for this topic?

**Comment by ramonskie** [comment]
yes its still open due to warden bosh-lite. as runc is still installed currently also to support `chpst` commands used in most bosh releases

**Comment by ramonskie** [comment]
can be closed after we merge #397

**Comment by beyhan** [comment]
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/397 has been merged.
