### ISSUE TITLE
Noble Numbat vSphere/vCloud stemcells forbid SSH password authentication

### ISSUE THREAD

**Issue by danielfor** [cloudfoundry/bosh-linux-stemcell-builder#323]
The Stemcells have the SSH password authentication disabled, with the exception of the stemcells created for vsphere/vcloud which allow password authentication.
It might be a good idea to standardize the SSH configuration in the Noble Numbat stemcells, so we don't have exceptions and all of them forbid password authentication, increasing security and avoiding scanners to find weaknesses in the vsphere stemcells.

**Comment by cunnie** [comment]
I think some vSphere users campaigned vociferously for an exception, and OpenStack, too, if memory serves.

**Comment by ramonskie** [comment]
is there anyway to figure out who campaigned for this? and check if this is still relevant.
as its pretty easy nowdays to add an ssh key to an existing stemcell tarball. if debug sessions are required.
see https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu_noble_poc/scripts/add_debug_ssh.sh

**Comment by ramonskie** [comment]
solved in #351
