### ISSUE TITLE
Noble: No longer cut vCloud stemcells

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh-linux-stemcell-builder#330]
https://en.wikipedia.org/wiki/VCloud_Air vCloud was sold to OVH in 2017. Probably can't use stemcells there anymore anyway.

**Comment by ramonskie** [comment]
agreed but we need to do some communication i think to ask who is still using vlcoud.
and would we remove/cleanup the vlcoud code?
or is the first step just removing the build stemcell from the ci

**Comment by ramonskie** [comment]
vlcoud is not availble anymore for noble see
https://github.com/cloudfoundry/bosh-stemcells-ci/blob/master/pipelines/ubuntu-noble/stemcells.yml
