### ISSUE TITLE
Noble revise the generate_dev_tools_file_list

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-linux-stemcell-builder#339]
we need to revise https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu_noble_poc/stemcell_builder/stages/dev_tools_config/assets/generate_dev_tools_file_list.sh

as package names changes etc

**Comment by beyhan** [comment]
We could also improve the test for this in https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/2aca0ec0b6cb9ec6248160bd2eef4cd8e2c881d0/bosh-stemcell/spec/stemcells/ubuntu_jammy_spec.rb#L132

**Comment by ramonskie** [comment]
improved it a bit with https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/cdfcb4f302018e4ace52567ef14bc0694f8dc1b2
