### ISSUE TITLE
bats and agent are still using sv commands

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-linux-stemcell-builder#345]
in the bosh acceptance tests we have hardcoded sv commands
for example: 
- https://github.com/cloudfoundry/bosh-acceptance-tests/blob/master/spec/system/cck_spec.rb#L24
- https://github.com/cloudfoundry/bosh-acceptance-tests/blob/master/spec/system/service_configuration_spec.rb#L314

and in the agent we also have sv commands
- https://github.com/cloudfoundry/bosh-agent/blob/main/jobsupervisor/monit_job_supervisor.go#L83
- https://github.com/cloudfoundry/bosh-agent/blob/main/platform/linux_platform.go#L1465

these should be configurable as in noble monit and the agent are being run by systemd

**Comment by ramonskie** [comment]
as now need to also know if we are using systemd  and we already have `DNSResolverType` config in the agent settings.
maby its time to have something generic.
or maby we do want to use different settings.

**Comment by jpalermo** [comment]
Agent work is currently happening [here](https://github.com/cloudfoundry/bosh-agent/pull/327/files)

**Comment by ramonskie** [comment]
(https://github.com/cloudfoundry/bosh-agent/pull/327/files) is merged
https://github.com/cloudfoundry/bosh-acceptance-tests/pull/50 merged
