### ISSUE TITLE
Public IaaS stemcells should use recommended NTP servers

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh-linux-stemcell-builder#346]
For example, AWS recommends using their NTP server of `169.254.169.123`.

This would allow stricter default security groups without worrying about allowing NTP traffic.

**Comment by ramonskie** [comment]
would't this be something for the bosh-deployment repo?

**Comment by jpalermo** [comment]
Yeah, this is [already a thing](https://github.com/cloudfoundry/bosh-deployment/blob/c82627a8ab9c2270f0da0852edb1d20e9a5aea06/misc/ntp.yml). No idea how I came to the conclusion that it was set directly within the stemcell...

**Comment by ramonskie** [comment]
Well i understand the confusion as we do set ntp for azure within the stemcell. As Azure uses a different protocol
