### ISSUE TITLE
50-default.conf in rsyslog.d results in errors

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/bosh-linux-stemcell-builder#35]
```2018-04-03T17:05:02.358719+00:00 localhost rsyslogd-2039: Could not open output pipe '/dev/xconsole':: No such file or directory [v8.22.0 try http://www.rsyslog.com/e/2039 ]```

As you can see above, it's trying to output logs to xconsole, but the stemcell does not seem to have an xconsole, or an x-server running(nor would I expect it to have one). This probably comes from the default ubuntu config, but does not make sense for a headless bosh vm.

**Comment by cppforlife** [comment]
@Benjamintf1 would you happen to know how to disable that if you think this is something that's not necessary?

**Comment by Benjamintf1** [comment]
On the last line 
```
daemon.*;mail.*;\
	news.err;\
	*.=debug;*.=info;\
	*.=notice;*.=warn	|/dev/xconsole
```
Remove the pipe to /dev/xconsole

```
daemon.*;mail.*;\
	news.err;\
	*.=debug;*.=info;\
	*.=notice;*.=warn
```

Or more probably even entirely

```
```

**Comment by Benjamintf1** [comment]
Stale
