### ISSUE TITLE
Noble - warden/boshlite

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-linux-stemcell-builder#352]
warden is currently not working on noble.
due to
- cgroups v2 #327 
- runit systemd #322

**Comment by ramonskie** [comment]
the following pr will support boshlite #397 
and a pr for warden cpi https://github.com/cloudfoundry/bosh-warden-cpi-release/pull/24

**Comment by beyhan** [comment]
Closing because the mentioned pr above has been merged.
