### ISSUE TITLE
grub-install: unknown filesystem error at 'image_install_grub' for GCP jammy stemcell

### ISSUE THREAD

**Issue by AJLfleos** [cloudfoundry/bosh-linux-stemcell-builder#376]
I was trying to build a GCP jammy stemcell from a linux working machine when I started to see odd errors complaining grub cannot recognize the filesystem at [grub-install](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-jammy/stemcell_builder/stages/image_install_grub/apply.sh#L72) part in that `image_install_grub` stage.

I tried to use `grub-probe` to check the `/dev/loop0` which also showed `unknown filesystem`

```
sudo grub-probe -d /dev/loop0 -v
grub-probe: info: cannot open `/boot/grub/device.map': No such file or directory.
grub-probe: info: /dev/loop0 is not present.
grub-probe: info: Looking for /dev/loop0.
grub-probe: info: /dev/loop0 is a parent of /dev/loop0.
grub-probe: info: /dev/loop0 is present.
grub-probe: info: Looking for /dev/loop0.
grub-probe: info: /dev/loop0 is a parent of /dev/loop0.
grub-probe: info: /dev/loop0 is present.
grub-probe: info: Looking for /dev/loop0.
grub-probe: info: /dev/loop0 is a parent of /dev/loop0.
grub-probe: info: opening hostdisk//dev/loop0.
grub-probe: info: drive = 0.
grub-probe: info: the size of hostdisk//dev/loop0 is 0.
grub-probe: error: unknown filesystem.
```

Any insights what could be the root-cause of such issue? Thanks

Full log print: https://gist.github.com/AJLfleos/8af3de3fa5fcb83a4795c3e75708e039

**Comment by AJLfleos** [comment]
Also, I found the machine I used seems to be using `EFI` secure boot, but I'm not sure if this is the root-cause. I thought in theory it should be allowed to build a stemcell in BIOS boot from machine using EFI boot.

```
sda                          8:0    0    4T  0 disk  
├─sda1                       8:1    0  3.7G  0 part  /boot/efi
├─sda2                       8:2    0  3.7G  0 part  /boot
└─sda3                       8:3    0    4T  0 part  
```

**Comment by jpalermo** [comment]
We always build the stemcell within the docker container mentioned in the Readme. That gives a consistent environment and prevents the builder from modifying the actual computer in a negative way.

**Comment by AJLfleos** [comment]
Yes, I ended up figuring out the root-cause. The machine I used has encrypted partition that `grub-installl` cannot work with. Using docker container with a stemcell builder dedicated docker image is indeed good to provide a machine-agnostic environment for stemcell building.
