### ISSUE TITLE
[noble] Missing files from installed packages causing executables to fail.

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-linux-stemcell-builder#380]
I tried running `host`, `dig`, and `nslookup` today on a noble stemcell and was greeted with `error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`. 

I did a verify of all dpkg packages on the stemcell and found 1546 files missing (presumably some intentionally to reduce bloat), but there seem to be a number of libraries caught up in the mix. Attaching the full output of missing files for review in case it's helpful:

[missing.txt](https://github.com/user-attachments/files/16880871/missing.txt)

**Comment by geofffranks** [comment]
Fun note - this also affects the `apt` command which makes it difficult to re-install the libstdc++6 package as a workaround 😂

**Comment by geofffranks** [comment]
After re-installing a manually downloaded libstdc++6, I also ran into the same issue with libgcc-s1.

**Comment by jpalermo** [comment]
Removed [a couple packages](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/46092d379c87fc6c1291004356e24d1d818d5ffe) from the dev list and `host`, `dig` and `nslookup` no longer throw errors. [0.99](https://github.com/cloudfoundry/bosh-io-stemcells-core-index/tree/main/dev/ubuntu-noble/0.99) is the build I was testing on
