### ISSUE TITLE
[xenial] ip6tables v1.6.0: can't initialize ip6tables table `filter': Address family not supported by protocol

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-linux-stemcell-builder#40]
On Xenial I'm getting:
```
# ip6tables  -w 30  -I  OUTPUT  1  -p  tcp  --dport 19080  -m comment --comment  'WindowsFabric:azure-service-fabric0 WindowsFabric Http Gateway (TCP-Public-Out)' -j ACCEPT
ip6tables v1.6.0: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
```

The `iptables` equivalent command works as expected.

Is this something fixable by me/my boshrelease, something fixable in stemcell, or elsewhere?

**Comment by cppforlife** [comment]
@drnic you might have to enable ipv6 kernel module via `env.bosh.ipv6.enable=true` on your instance group: http://bosh.io/docs/manifest-v2/#instance-groups

**Comment by drnic** [comment]
Thanks, that fixed my issue!
