### ISSUE TITLE
[xenial] v4.15 kernel hangs on Azure if SR-IOV is enabled

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-linux-stemcell-builder#47]
I use the stemcell xenial v40 to deploy CF on Azure with [accelerated networking (SR-IOV)](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli) enabled. The VM hangs with `watchdog: BUG: soft lockup - CPU#2 stuck for 22s!`.
Detailed logs: [09d9a3c0-2ea6-4e68-9e98-0f1c00928c31.860db4a3-01fe-4f10-a97b-38283bc4cd64.serialconsole.txt](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/files/2042645/09d9a3c0-2ea6-4e68-9e98-0f1c00928c31.860db4a3-01fe-4f10-a97b-38283bc4cd64.serialconsole.txt)

This should be fixed by https://github.com/torvalds/linux/commit/de0aa7b2f97d348ba7d1e17a00744c989baa0cb6#diff-a9cd8181fe90643b51b4a77e48556743, which is released as `4.17-rc1`.
Is there a plan to upgrade the kernel in the ubuntu xenial stemcell? Thanks.

**Comment by cppforlife** [comment]
@bingosummer i would recommend escalating this to canonical from microsoft side so that they include it in `linux-generic-hwe-16.04-edge` package.

**Comment by bingosummer** [comment]
Thanks @cppforlife . Will try your suggestion.

**Comment by bingosummer** [comment]
Update: The version [`4.15.0.23.45` of linux-generic-hwe-16.04-edge](https://www.ubuntuupdates.org/package/core/xenial/main/proposed/linux-generic-hwe-16.04-edge) contains this change. But it's still in `proposed` level.

**Comment by bingosummer** [comment]
Update: the package has been released as `updates` level.
The next periodic Ubuntu Xenial stemcell bump should be able to contain the fix.

**Comment by cppforlife** [comment]
`ii  linux-generic-hwe-16.04-edge  4.15.0.24.46` is what in the latest stemcells, so im going to close this issue.
