### ISSUE TITLE
Project quota support missing from e2fsprogs

### ISSUE THREAD

**Issue by ostenbom** [cloudfoundry/bosh-linux-stemcell-builder#49]
Xenial has support for project quotas (directory quotas) using ext4 in the kernel, but the [version of e2fsprogs availabe on xenial](https://packages.ubuntu.com/xenial/admin/e2fsprogs) is too low to make use of this feature (v1.43+ required).

We are exploring how we deal with container quotas on garden. Rather than quotas working through a xfs formatted sparse file on a loopback device, we would like /var/vcap/data to be mounted with the project quota option enabled. How might it be possible to get a newer version of e2fsprogs compiled on new stemcells?

**Comment by mrosecrance** [comment]
Closing as stale
