### ISSUE TITLE
RANDOM_DELAY in anacrontab is not applied

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh-linux-stemcell-builder#5]
`RANDOM_DELAY` is currently appended to the end of `anacrontab` (at least on ubuntu stemcells):
```
$ cat /etc/anacrontab
# /etc/anacrontab: configuration file for anacron

# See anacron(8) and anacrontab(5) for details.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
HOME=/root
LOGNAME=root

# These replace cron's entries
1       5       cron.daily      run-parts --report /etc/cron.daily
7       10      cron.weekly     run-parts --report /etc/cron.weekly
@monthly        15      cron.monthly    run-parts --report /etc/cron.monthly

RANDOM_DELAY=60
```

as can be seen in the anacron source code, `RANDOM_DELAY` only applies to cron entries that follow it: https://github.com/cronie-crond/cronie/blob/b836b5789cae7d608346d64e64ade121d8608518/anacron/readtab.c#L304 (this is not clear from the documentation, but it's worth pointing out that all `anacrontab(5)` examples in the docs put `RANDOM_DELAY` before the cron entries)

we noticed this because if a `RANDOM_DELAY=60` was really into effect the following would return a much more even distribution (just for context `runsrv dea` runs the command against all of our 9 lab deas):

```
$ runsrv dea 'sudo zgrep /etc/cron.hourly /var/log/syslog*' | cut -d: -f3 | sort | uniq -c
   5214 17
      9 22
$ runsrv dea 'sudo zgrep /etc/cron.daily /var/log/syslog*' | cut -d: -f3 | sort | uniq -c
      9 23
    215 25
$ runsrv dea 'sudo zgrep /etc/cron.weekly /var/log/syslog*' | cut -d: -f3 | sort | uniq -c
      9 23
     34 47
$ runsrv dea 'sudo zgrep /etc/cron.monthly /var/log/syslog*' | cut -d: -f3 | sort | uniq -c
      9 23
      9 52
```

When running on on-premise infrastructure it's pretty important for cronjobs not to run at the same time to avoid gratuitous spikes. The most desirable behaviour, at least from our perspective, would be for all VMs to run the cronjobs at slightly different times.

**Comment by cppforlife** [comment]
will be in the upcoming new major version stemcell: https://www.pivotaltracker.com/story/show/145355805

**Comment by cppforlife** [comment]
3421.x stemcell should have this fixed. thanks for reporting.
