### ISSUE TITLE
logger could not write to `/var/log/syslog` file

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-linux-stemcell-builder#64]
Hi, I am stemcell builder: https://github.com/bluebosh/bosh-linux-stemcell-builder/tree/ubuntu-xenial-ng

And my stemcell could not passed smoke test: when syslog threshold limit is reached should rotate the logs 

https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/60646ed27bc7b8dc6be6f589a2162b4c0a2e7280/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go#L45

I ran these command mannully and logrotate worked well(rotate logs larger than 10MB) but **logger** command could not write to `/var/log/syslog`. So this case failed.

I could not find your builder pipeline logs. So I had to ask you. Did you see same issues?

Thank you!

**Comment by jrussett** [comment]
Hi @edwardstudy,

We have not seen this failure in our CI on both the `ubuntu-xenial` and `ubuntu-trusty` stemcell lines. 

Going to close this issue now. Please feel free to reopen this if you had another question about it.

Thanks,
@jrussett && @jfmyers9, CF BOSH

**Comment by edwardstudy** [comment]
Thanks. I just needed a confirmation. @jrussett Hi, I just found it write to `/var/log/user.log`.
