### ISSUE TITLE
Update outdated s3cli version

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry/bosh-linux-stemcell-builder#78]
Please bump s3cli to the latest version. This is needed as the currently included version causes issues when using alicloud OSS as blobstore for the BOSH director.

While compiling you'll receive the error `performing operation get: AccessDenied: OSS authentication requires a valid Date.` 

This is caused by a wrong Date format ( using UTC instead of GMT ) in the request header. 
This issues was fixed with version v0.0.80 which is already part of the latest version of the BOSH Director.

**Comment by aashah** [comment]
Merged PR. Gonna close this issue, please feel free to re-open if something doesn't look right :thinking:
