### ISSUE TITLE
[xenial] nvidia gpu support

### ISSUE THREAD

**Issue by alekssaul** [cloudfoundry/bosh-linux-stemcell-builder#90]
Hi,

I was interested to understand the possibility of using nvidia GPUs with CFCR/PKS however I had issues with getting nvidia drivers running on the Xenial stemcells. `nouveau` kernel modules seem to be enabled by default and runtime removal of the module seem to cause a panic on stemcell. 

I wanted to open a thread to discuss if it would be possible to blacklist `nouveau` 

+ @svrc

**Comment by aashah** [comment]
Hello, closing this in favor of discussing the change in the PR.

Please feel free to re-open if you feel otherwise!
