### ISSUE TITLE
Unable to create loopback devices in Ubuntu Xenial

### ISSUE THREAD

**Issue by fenech** [cloudfoundry/bosh-linux-stemcell-builder#92]
I am trying to run a Concourse deployment on a BOSH Lite director, which uses the Ubuntu Xenial stemcell (downloaded from https://bosh.cloudfoundry.org/stemcells/bosh-warden-boshlite-ubuntu-xenial-go_agent).

My problem is that the OS doesn't seem to support loopback devices:
```
worker/5ad0b4d9-1e30-46e3-892c-14554dec5629:~$ losetup -l
worker/5ad0b4d9-1e30-46e3-892c-14554dec5629:~$ losetup -f
losetup: cannot find an unused loop device: No such file or directory
```
This means that the Concourse worker fails. This appears to be a regression, since I am following the instructions from https://github.com/concourse/concourse-bosh-deployment/tree/master/cluster which suggest that it is possible to run in this configuration.

**Comment by christarazi** [comment]
Are you still experiencing problems? If so, please re-open.
