### ISSUE TITLE
[It] should fail to get logs, but the deploy should succeed 

### ISSUE THREAD

**Issue by xiaozhu36** [cloudfoundry/bosh-linux-stemcell-builder#98]
When I use the [Alibaba Cloud Bosh CPI](https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release) and the latest [Alibaba Cloud stemcell](https://bosh.io/stemcells/bosh-alicloud-kvm-ubuntu-xenial-go_agent) to run the smoke test, there always happens a panic error:
```
Task 91 | 10:46:53 | Updating instance default: default/6331b3fd-e16c-4316-80e6-566742343562 (0) (canary) (00:02:22)
[Cmd Runner] 2019/07/20 10:49:19 DEBUG - Stderr: 
[Cmd Runner] 2019/07/20 10:49:19 DEBUG - Successful: true (0)
•! Panic [161.830 seconds]
Stemcell #164749230, when using targeted blobstores when deploying with a invalid logs blobstore [It] should fail to get logs, but the deploy should succeed 
/tmp/build/82c27cda/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go:309

  Test Panicked
  runtime error: index out of range
  /usr/local/go/src/runtime/panic.go:44

  Full Stack Trace
  	/usr/local/go/src/runtime/panic.go:522 +0x1b5
  github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke_test.glob..func3.11.2.1()
  	/tmp/build/82c27cda/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go:328 +0x1664
  github.com/cloudfoundry/stemcell-acceptance-tests/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0000734a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/tmp/build/82c27cda/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_suite_test.go:18 +0x64
  testing.tRunner(0xc0000ece00, 0x898db0)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
```
By debug, I noticed the [config](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go#L319) always a nil struct and the length of [Blobstores](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go#L328) always is 0. So I changed the [blobStoreVars](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go#L327) by the following:
```
				bsv := blobStoreVars{}
				if len(config.Env.BoshEnv.Blobstores) > 0 {
					bsv.Endpoint=             config.Env.BoshEnv.Blobstores[0].Options.Endpoint
					bsv.BlobstoreAgentPassword= config.Env.BoshEnv.Blobstores[0].Options.Password
					bsv.BlobstoreCaCertificate= config.Env.BoshEnv.Blobstores[0].Options.Tls.Cert.Ca
				}
```
After that, I retry and got another error:
```
Task 95 | 12:23:18 | Updating instance default: default/4caea898-9773-4f9b-906e-b2abedd3a50e (0) (canary) (00:02:13)
[Cmd Runner] 2019/07/21 12:25:33 DEBUG - Stderr: 
[Cmd Runner] 2019/07/21 12:25:33 DEBUG - Successful: true (0)
• Failure [305.064 seconds]
Stemcell #164749230, when using targeted blobstores when deploying with a invalid logs blobstore [It] should fail to get logs, but the deploy should succeed 
/tmp/build/82c27cda/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go:309

  Expected an error to have occurred.  Got:
      <nil>: nil

  /tmp/build/82c27cda/bosh-linux-stemcell-builder/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go:354
```
I also found it always will be success whatever I setting any values for the `add-invalid-logs-blobstore.yml` and there is no any error.

Is there any ideas to fix it?

In addition, this CI pipeline is [bosh-cpi-certification of alicloud](https://github.com/aliyun/bosh-cpi-certification/tree/master/alicloud) and this error same as [invalid packages blobstore](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/src/github.com/cloudfoundry/stemcell-acceptance-tests/ipv4director/smoke/smoke_test.go#L353)

**Comment by aashah** [comment]
Hey @xiaozhu36,

I took a look at the test that is failing for you, and I believe we'll actually be deleting the test soon.

We're planning to move away from fairly recent (un-released) feature in favor of a different solution. The background for this was to provide a better solution for securing blobstore credentials. Our new epic is https://www.pivotaltracker.com/epic/show/4378712

Here's a story intended on removing this `targeted_blobstores` config - https://www.pivotaltracker.com/story/show/165892429

If that all sounds okay, can you close this issue in favor of the stories in our Tracker project?

- Aakash
BOSH Systems

**Comment by xiaozhu36** [comment]
HI @aashah Thanks for your feedback. It sounds great and waiting for your good news. By the way, is there any ETA for it?

**Comment by aashah** [comment]
That track of work is our second highest prioritized epic (outside Bionic), so hopefully soon. Following the Tracker story will give you the most up to date estimate though.

**Comment by xiaozhu36** [comment]
HI @aashah I noticed the story https://www.pivotaltracker.com/n/projects/2238419/stories/165892429 is still in Unstarted. Is there any progress or ETA on it?

**Comment by aashah** [comment]
@xiaozhu36 Just finished it out. Thanks for the ping.

Removing the test should obviously make it go green, please feel free to re-open if something related to the change breaks.

**Comment by xiaozhu36** [comment]
@aashah Thanks for your feedback and I will try again. But the CI also have another issue #97 and does it have any ideas?
